Revert r336497 for now, as it breaks on architectures using gcc, with:
cc1: warnings being treated as errors
/usr/src/lib/msun/src/s_cpow.c: In function 'cpow':
/usr/src/lib/msun/src/s_cpow.c:63: warning: implicit declaration of function 'CMPLX'


git-svn-id: svn+ssh://svn.freebsd.org/base/head@336500 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f